version: '3'
services:
  redis-db:
    container_name: dynamo-db-container
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"
  study-web-app:
    restart: always
    container_name: study-spring-dynamodb-app
    depends_on:
      - dynamo-db-container
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_KEY=
    ports:
      - "8081:8080"
    volumes:
      - ./build/libs/docker-app.jar:/usr/app/application.jar